### ISSUE TITLE
Files to cleanup

### ISSUE THREAD

**Issue by gsaponaro** [vislab-tecnico-lisboa/foveated_stereo#1]
Hi @ruipimentelfigueiredo :)

Just a list of files that are committed to this repository but probably should be deleted in a future cleanup:
* matlab/foveal_stereo_back.m
* matlab/foveal_stereo_backup.m
* matlab/HVS/test.m <- not sure about this
* matlab/ROS/test.m <- not sure about this
* matlab/ROS/untitled.m
* matlab/datasets/test.m
* src/EgoSphere.h_back
* src/stereo_sensors/logpolar.cppback
* src/stereo_sensors/logpolar.hppback

**Comment by ruipimentelfigueiredo** [comment]
Thanks for noticing @gsaponaro! Removed unused/backup files on commit 15d329746dce750b30ac05a251276fc90fe01782
